version: '3.8'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./db/.env
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    networks:
      - citybikes-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      - citybikes-network
  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - citybikes-network
    restart: always
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - citybikes-network
    restart: always
networks:
  citybikes-network:
    name: citybikes-network
